[package]
name = "filelock"
version = "0.5.0"
edition = "2024"
description = "Cross-platform file locking library for Rust"
authors = ["AN Long<aisk1988@gmail.com>"]
repository = "https://github.com/aisk/filelock"
license = "MIT"
readme = "README.md"
keywords = ["file", "lock", "flock", "locking", "mutex"]
categories = ["filesystem", "concurrency"]

[dependencies]
errno = "^0.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0.3", features = ["handleapi", "fileapi"] }

[target.'cfg(unix)'.dependencies]
libc = "^0.2"
